spring:
  datasource:
    password: gsilva11
    username: gusto
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transportador
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5Dialect'
    hibernate:
      ddl-auto: update
