server:
  port: 8888 

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Gustomize/microservices/tree/master/microservices-repo/
          search-paths: fornecedor