server:
  port: 8888 

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Gustomize/microservices/
          search-paths: microservices-repo/fornecedor, microservices-repo/loja, microservices-repo/transportador 